main.nf

Just updating to include the latest changes

Latest changes 

---

main.nf

Channel mix missing

---

.gitignore
conf/base.config
main.nf
runBcellmagic.sh

This improves especially handling of resource requirements.

Quite some improvements

---

conf/base.config
main.nf

Many thanks to contributing to nf-core/bcellmagic!

Some minor fixes 

---

Dockerfile
bin/TIgGER-shazam.R
main.nf
nextflow.config

This should do it - lets test tomorrow!

Use sets where applicable

---

Dockerfile

Bump dockerfile

---

main.nf

Replace filenames with IDs from the metadata table!

Use all the IDS!

---

main.nf

Fixed bug where fasta files were mixed between igblast and igblast_filter from different samples.

fixed bug fasta files handling

---

.travis.yml
README.md
bin/log_parsing.py
conf/base.config
main.nf
nextflow.config

- Added logging in each of the processes so that the sequence numbers after each of the processes can be extracted for quality control.
- Added possibility of running only define clones processes on pre-existing changeo tables (allows to define clones patient-wise).
- Added parameter to define specific threshold for clone calculation

Added logging and define clone features

---

Dockerfile
environment.yml

Many thanks to contributing to nf-core/bcellmagic!
This fixes #34. Now the linting process must work.

fix linting errors

---

CHANGELOG.md
Dockerfile

fixed dockerfile

---

.travis.yml
Dockerfile
environment.yml
nextflow.config

bump version 1.1.0

---

README.md
main.nf

review requested changes

---

Dockerfile

removing symlink from container

remove symlink container

---

.github/workflows/awstest.yml
CHANGELOG.md
bin/merge_R1_umi.py
conf/test.config
docs/usage.md
main.nf
nextflow.config
nextflow_schema.json

Allow variable UMI start position in index file.

Add UMI start position option

---

CHANGELOG.md
bin/lineage_reconstruction.R
main.nf

- Fixing lineage reconstruction publish of clone svg plots and graphml file
- Shortening filename in assemble process to avoid problems due to too long filename downstream

Lineage reconstruction publish

---

.github/workflows/awsfulltest.yml

test with job name

---

.github/workflows/awstest.yml

test again

---

.github/workflows/awstest.yml

yet another test

---

.github/workflows/ci.yml
CHANGELOG.md
bin/log_parsing.py
conf/test.config
conf/test_tcr.config
main.nf
nextflow.config

- Add tests for TCR data
- Fix log parsing order

Add test TCR, fix logs order

---

CHANGELOG.md
conf/test_full.config
nextflow.config

add full test config

---

CHANGELOG.md
modules/local/presto/presto_pairseq.nf

Fix barcode copy pairseq

---

modules/local/fetch_databases.nf

update container fetchdatabases

---

CHANGELOG.md
bcellmagic.nf
modules/local/changeo/changeo_makedb.nf

MakeDB not restricted to heavy chains

---

docs/output.md

fix output md

---

README.md
assets/references.bibtex
assets/repertoire_comparison.Rmd

Add citations bibtex report

---

assets/references.bibtex
assets/repertoire_comparison.Rmd

fix reference

---

CHANGELOG.md
modules/local/alakazam/alakazam_shazam_repertoires.nf
workflows/bcellmagic.nf

Update channels report

---

CHANGELOG.md
bin/shazam_threshold.R
conf/modules.config
modules/local/shazam/shazam_threshold.nf

- Fix hamming threshold for TCR sequences: no plot generation as it was giving errors.
- Make Hamming threshold pdf plot optional for the `shazam_threshold` process.
- Remove warnings of processes for alternate workflows.

Fix TCR hamming threshold

---

.github/workflows/ci.yml
CHANGELOG.md
assets/repertoire_comparison.Rmd
conf/test_tcr_thr.config
nextflow.config
workflows/bcellmagic.nf

- Skip shazam process if the threshold is provided

Skip shazam if threshold is provided

---

workflows/bcellmagic.nf

Fix skip-lineage

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/awsfulltest.yml
.github/workflows/awstest.yml
.gitpod.yml
CHANGELOG.md
workflows/bcellmagic.nf

nf-core v2.3.2 template updates

---

docs/usage.md

Updated docs, to add experimental features (reveal)

---

CHANGELOG.md
nextflow.config

Bump versions to 2.1.0

---

assets/repertoire_comparison.Rmd
bin/lineage_reconstruction.R
bin/log_parsing.py
bin/shazam_threshold.R
conf/modules.config
conf/test_full.config
docs/output.md

Apply review comments

---

CHANGELOG.md

Add release date and update changelog

---

.github/workflows/awsfulltest.yml
.github/workflows/awstest.yml
.github/workflows/branch.yml
.github/workflows/ci.yml
.github/workflows/fix-linting.yml
.github/workflows/linting.yml
.github/workflows/linting_comment.yml
.prettierignore
CHANGELOG.md
README.md
assets/email_template.html
conf/modules.config
conf/test.config
conf/test_fetchimgt.config
conf/test_full.config
conf/test_no_umi.config
conf/test_nocluster.config
conf/test_reveal.config
conf/test_reveal_no_cc.config
conf/test_tcr.config
conf/test_tcr_thr.config
modules/local/changeo/changeo_assigngenes.nf
modules/local/fetch_databases.nf
modules/local/samplesheet_check.nf
modules/local/unzip_db.nf
nextflow.config
workflows/bcellmagic.nf
workflows/reveal.nf

Template update v2.4.1

---

.github/workflows/ci.yml
CHANGELOG.md
conf/test.config
conf/test_fetchimgt.config
conf/test_full.config
conf/test_no_umi.config
conf/test_nocluster.config
conf/test_reveal.config
conf/test_reveal_no_cc.config
conf/test_tcr.config
conf/test_tcr_thr.config
modules/local/fetch_databases.nf
nextflow.config

Try fixing reveal tests [DO NOT MERGE]

---

CHANGELOG.md
conf/modules.config
nextflow.config

Prepare release 2.2.0

---

CHANGELOG.md
nextflow.config

version bump for release

---

bin/check_samplesheet.py
conf/modules.config
conf/test_assembled.config
modules/local/enchantr/collapse_duplicates.nf
modules/local/enchantr/define_clones.nf
modules/local/enchantr/detect_contamination.nf
modules/local/enchantr/dowser_lineages.nf
modules/local/enchantr/find_threshold.nf
modules/local/enchantr/remove_chimeric.nf
modules/local/enchantr/report_file_size.nf
modules/local/enchantr/single_cell_qc.nf
modules/local/enchantr/validate_input.nf
subworkflows/local/bulk_germlines_and_filter.nf
subworkflows/local/clonal_analysis.nf
workflows/airrflow.nf

Merge bcellmagic and reveal workflows
Use subworkflows to structure the code

Merge bcellmagic and reveal workflows

---

conf/modules.config
conf/test_immcantation_devel.config
modules/local/enchantr/define_clones.nf
modules/local/enchantr/dowser_lineages.nf
modules/local/enchantr/single_cell_qc.nf
modules/local/enchantr/validate_input.nf

scqc outs multiple dbs, update modules and paths

---

CHANGELOG.md
nextflow.config

Bump versions for 2.4.0 release

---

modules/local/enchantr/collapse_duplicates.nf
modules/local/enchantr/define_clones.nf
modules/local/enchantr/detect_contamination.nf
modules/local/enchantr/dowser_lineages.nf
modules/local/enchantr/find_threshold.nf
modules/local/enchantr/remove_chimeric.nf
modules/local/enchantr/report_file_size.nf
modules/local/enchantr/single_cell_qc.nf
modules/local/enchantr/validate_input.nf
modules/local/reveal/add_meta_to_tab.nf
modules/local/reveal/filter_junction_mod3.nf
modules/local/reveal/filter_quality.nf
nextflow.config

Update enchantr to 0.0.6

---

conf/modules.config
modules/local/enchantr/find_threshold.nf
nextflow.config
nextflow_schema.json

added crossby

---

assets/repertoire_comparison.Rmd
conf/modules.config

try fix error problem pandoc

---

assets/repertoire_comparison.Rmd

Fix Airrflow report

---

modules/local/airrflow_report/airrflow_report.nf
modules/local/enchantr/collapse_duplicates.nf
modules/local/enchantr/define_clones.nf
modules/local/enchantr/detect_contamination.nf
modules/local/enchantr/dowser_lineages.nf
modules/local/enchantr/find_threshold.nf
modules/local/enchantr/remove_chimeric.nf
modules/local/enchantr/report_file_size.nf
modules/local/enchantr/single_cell_qc.nf
modules/local/enchantr/validate_input.nf
modules/local/reveal/add_meta_to_tab.nf
modules/local/reveal/filter_junction_mod3.nf
modules/local/reveal/filter_quality.nf

Update EnchantR build

---

CHANGELOG.md
assets/samplesheet_full_test.tsv
conf/test_full.config

add full tests sra bucket paths

---

bin/reveal_filter_quality.R
modules/local/igblast/igblast_assigngenes.nf

Filter out sequences with NA in v_call, d_call and j_call

---

CHANGELOG.md
assets/repertoire_comparison.Rmd
modules/local/airrflow_report/airrflow_report.nf
modules/local/enchantr/collapse_duplicates.nf
modules/local/enchantr/define_clones.nf
modules/local/enchantr/detect_contamination.nf
modules/local/enchantr/dowser_lineages.nf
modules/local/enchantr/find_threshold.nf
modules/local/enchantr/remove_chimeric.nf
modules/local/enchantr/report_file_size.nf
modules/local/enchantr/single_cell_qc.nf
modules/local/enchantr/validate_input.nf
modules/local/reveal/add_meta_to_tab.nf
modules/local/reveal/filter_junction_mod3.nf
modules/local/reveal/filter_quality.nf

Update to EnchantR 0.1.1

---

CHANGELOG.md
nextflow.config

Bump version 3.0

---

.github/workflows/ci_immcantation.yml
CHANGELOG.md

ci container do not run on master

---

bin/fetch_imgt.sh

Imgt url fix

---

CHANGELOG.md
conf/modules.config
docs/output.md
modules/local/enchantr/dowser_lineages.nf
modules/local/enchantr/find_threshold.nf
modules/local/presto/presto_buildconsensus.nf
nextflow.config
nextflow_schema.json
subworkflows/local/clonal_analysis.nf

- Fix documentation
- Pull docker container and convert to singularity when running with singularity
- Parametrize Findthreshold Report threshold

Short term fix issues Dowser singularity container

---

assets/schema_input.json
main.nf

- fix validate params as new plugin is working
- allow tissue whitespaces
- allow whitespaces sex

fix validate params

---

README.md
modules/local/enchantr/collapse_duplicates.nf
modules/local/enchantr/define_clones.nf
modules/local/enchantr/detect_contamination.nf
modules/local/enchantr/dowser_lineages.nf
modules/local/enchantr/find_threshold.nf
modules/local/enchantr/remove_chimeric.nf
modules/local/enchantr/report_file_size.nf
modules/local/enchantr/single_cell_qc.nf
modules/local/enchantr/validate_input.nf
subworkflows/local/clonal_analysis.nf

- implement review changes
- rm define clones from report file size
- fixes runs on AWS fusion

Apply reviews

---

CHANGELOG.md
assets/repertoire_comparison.Rmd
conf/modules.config
modules/local/airrflow_report/airrflow_report.nf

Fix sequence plot in airrflow report

---

bin/fetch_igblastdb.sh

updated nih url to add nlm

---

conf/test_full.config

- Dowser tips by isotype
- update changelog
- isotype also for full test
- use raxml by default
- fix test full config
- update enchantr version
- fix prettier
- more raxml changes
- add profile info to readme
- fix comma
- skip lineage trees by default
- change version to 4.0.0
- oops fix container tag
- revert changes test full

Revert changes test_full

---

conf/test_full.config

Fix test full profile

---

CHANGELOG.md
docs/usage.md
modules/local/airrflow_report/airrflow_report.nf
modules/local/enchantr/collapse_duplicates.nf
modules/local/enchantr/define_clones.nf
modules/local/enchantr/detect_contamination.nf
modules/local/enchantr/dowser_lineages.nf
modules/local/enchantr/find_threshold.nf
modules/local/enchantr/remove_chimeric.nf
modules/local/enchantr/report_file_size.nf
modules/local/enchantr/single_cell_qc.nf
modules/local/enchantr/validate_input.nf
modules/local/reveal/add_meta_to_tab.nf
modules/local/reveal/filter_junction_mod3.nf
modules/local/reveal/filter_quality.nf

Immcantation version bump

---

docs/usage/bulk_tutorial.md
docs/usage/single_cell_tutorial.md
ro-crate-metadata.json

fix tutorial formatting errors

---

CHANGELOG.md
nextflow.config
ro-crate-metadata.json

Downgrade nf-schema and bump-versions

---

.github/workflows/awsfulltest.yml
CHANGELOG.md
nextflow.config
ro-crate-metadata.json

bump versions 4.3.1
